config/routes.rb
Rails.application.routes.draw do

 mount ActionCable.server => '/cable'
 
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end


  
 resources :blogs do
  resources :comments
 end

  get '/api' => "blogs#api"

  get "/profile/:id" => "profile#show", as: 'user_profile'
  get '/landing' => "blogs#landing", as: 'blogs_landing'

  patch "/users/:id", to: "user#update", as: 'edit_profile_favorites'
  
  devise_for :users
  
  root 'blogs#index'
  # resources :blogs

  resources :categories do
      member do
        put "like" => "blogs#upvote"
        put "dislike" => "blogs#downvote"
      end
  end


  resources :blogs do
      member do
        put "like" => "blogs#upvote"
        put "dislike" => "blogs#downvote"
      end
  end

  resources :users

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	acts_as_votable
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :blogs
	has_many :favorites
	has_many :users, through: :categories
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users
	has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :category

end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :chatroom
	belongs_to :user
	after_create_commit {BroadcastMessageJob.perform_later self}
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
  has_many :blogs, dependent: :destroy
  has_many :comments
  has_many :favorites
  has_many :categories, through: :favorites
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages  


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :index, :show, only:[:upvote, :downvote]
  before_action :authenticate_user!

  require 'news-api'
  
  def index
  	@blogs = Blog.all.order(:cached_votes_score => :desc)
    @messages = Message.all

  end

  def new
  	@blog = Blog.new
  end

  def create
  	
    @blog = Blog.new(blog_params)
  	@blog.user_id = current_user.id

  	if @blog.save
  		redirect_to "/"
  	else
  		render "/blogs/new"
  	end
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

    def update
      @blog = Blog.find(params[:id])
      if @blog.update(blog_params)
        redirect_to "/blogs"
      else
        render edit_blog_path
      end
    end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to "/blogs"
  end

  def upvote
    @blog.upvote_from current_user
    redirect_to blogs_path

  end

  def downvote
    @blog.downvote_from current_user
    redirect_to blogs_path
  end

  def landing
    
  end

  def api
    $newsapi = News.new("c1f1d9a225f348baab718198cab1037e")
    @top_headlines=$newsapi.get_top_headlines(sources: "espn")

    # if @top_headlines.save
    #   redirect_to "/profile/:id"
    # else
    #   render "/api"
    # end

  end

 

	private
def blog_params
	params.require(:blog).permit(:title, :content, :category_id, :user_id, :image, :remove_image)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  	def index
    	@comments = Comment.all
  	end
  	def new
    	@comment = Comment.new
  	end

	def create
		user = current_user
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		blog = Blog.find(params[:blog_id])
		@comment.blog_id = blog.id
		# @comment = @blog.comments.build(params[:comment])
		if @comment.save
			redirect_to "/blogs/#{params[:blog_id]}"
		else
			render "/blogs/#{params[:blog_id]}"
		end
	end


	def show
		@comment = Comment.find(params[:id])

	end

	def edit
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
	end

	
	def update
  		@blog = Blog.find(params[:blog_id])
  		@comment = @blog.comments.find(params[:id]) 
  		if @comment.update(comment_params)
    		redirect_to blog_path(@blog)
  		else
    		render :action => :edit
  		end   
	end




	def destroy
	  @blog = Blog.find(params[:blog_id])
	  @comment = @blog.comments.destroy(params[:id]) 
	redirect_to blog_path(@blog)  
 	end





	private
	
	def comment_params
		params.require(:comment).permit(:content, :user_id, :blog_id)
	end



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_chatroom
	
	

	def create
		message = @chatroom.messages.new(message_params)
		message.user = current_user
		message.save
		redirect_to @chatroom
		# MessageRelayJob.perform_later(message)
	end

	


	private

	def set_chatroom
		@chatroom = Chatroom.find(params[:chatroom_id])
	end

	def message_params
		params.require(:message).permit(:body)
	end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@messages = Message.all
  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def update
    @user = current_user
    @user.favorites.each do |favorite|
      favorite.destroy
    end
    user_params[:category_ids].each do |id|
    	if id != ""
		    Favorite.create(user_id: @user.id, category_id: id)
    	end
    end
    redirect_to user_profile_path(@user)
  end

 


  protected

  def user_params
    params.require(:user).permit(category_ids: [])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chatroom_users_helper.rb
module ChatroomUsersHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/api.html.erb
<div class = 'sportheader'>
	<h2>Live Sports Headline Feed: </h2>
</div>

	<div class="container-fluid">
		<div class="row content">
			<div class="col-md-2 sidenav">
		    	<div class = "favoritescontainer"></div>
		    </div>
			<div class="col-md-7">
				<div class = "postcontainer">

					<%@top_headlines.each do |t|%>
					<p><strong>Title: </strong> <%=link_to t.title, t.url%></p>
					<p><strong>Author: </strong><%=t.author %></p>
					<div class="description"><strong>Description:<br /> </strong><%=t.description%>
						<div class="imgsrc">
							<img src ="<%=t.urlToImage%>">
						</div>
					</div><hr>
					

					<%end%>
				</div>
			</div>
		</div>
	</div>

app/views/blogs/edit.html.erb
<div class = "articleheader"><h2>Article Update:</h2></div>




<div class="container-fluid">
	<div class="row content">
		<div class="col-md-9"> 
			<!-- Update Article Post (Start) -->
			<div class = "updatecontainer">
				<%= form_for @blog do |u| %>
					Title: <%= u.text_field :title %><br />
					Sport: <%= @blog.category.title %><br />
					<div class = "updatesubmit">
						<%= u.submit "Update" %>
					</div>
					<hr>
					<div class = "upcontentheader"> Article Content:</div><br />
					 <div class = "updatecontent"><%= u.text_area :content, :cols => 50, :rows => 8 %></div>
					 <br />
					<div class="field">
					    <%= u.label :Uploaded_Images %><br>
					    <%= u.file_field :image %>
					    <% if u.object.image? %>
				     		 <%= image_tag u.object.image.thumb.url %>
				     		 <%= u.label :remove_image %>
				      		 <%= u.check_box :remove_image %> 
				      	<% end %>	
				  	</div><br>
						

				<% end %>
				<!-- Update Article Post (End) -->
			</div>
		</div>
	</div>
</div>	

app/views/blogs/index.html.erb
<div class = 'sportheader'>
	<h2>The Main Feed: </h2>
</div>

	<div class="container-fluid">
		<div class="row content">
			<!-- Current Individual Categories A User 'Can Save' (Start)  -->
		    <div class="col-md-2 sidenav">
		    	<div class = "favoritescontainer">
					<% if user_signed_in?%>
							<strong><h2>Favorites:</h2></strong>
								<%= form_for current_user, html: { method: :patch } do |f| %>	
								
									<%= collection_check_boxes(:user, :category_ids, Category.all, :id, :title) %>
								
									<%= f.submit 'Save', data: { disable_with: false } %>
								<% end %>
					<% end %>
				</div>
			</div>
			<!-- Current Individual Categories A User 'Can Save' (End)  -->

			<!-- All Posted Listed (Start) -->
			<div class="col-md-8">
				<div class = "postcontainer">
					<% @blogs.each do |b| %>
						<a href = "/blogs/<%= b.id %>">Article Post: </a><br />
							<strong>Sport:</strong> <%= b.category.title if b.category %><br />

						<!-- Likes and Dislikes Functionality (Start) -->
							<div class ="caption" style= "text-align:left;">
								<%=link_to like_blog_path(b), class: "like", method: :put do %>
									<button type= "button" class="btn btn-info" aria-label="Left_Align">
										<span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
										<span class="badge"><%= b.get_upvotes.size %></span>
									</button>
								<% end %>
								<%=link_to dislike_blog_path(b), class: "dislike", method: :put do %>
									<button type= "button" class="btn btn-info" aria-label="Left_Align">
										<span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
										<span class="badge"><%= b.get_downvotes.size %></span>
									</button>
								<% end %>
							</div>
						<!-- Likes and Dislikes Functionality (End) -->
						<div class="post-container">
						  	
						  	<img src="<%= b.image.url()%>"/>

						<!-- Article Content Section Starts -->
							<div class = "textboxes">
								<strong><h3>Title: <%= b.title %></h3></strong>
								<br />
								<%= b.content %>
							</div><br />
			
						</div> 		
						<!-- Article Content Section Ends -->

							<!-- Comments Section Starts -->
							<div class="commentsection"><strong><h3>Comments Section:</h3></strong>
								<% b.comments.each_with_index do |c, index| %><br />
									 <a href="" class="message_username"><%= current_user.email %></a><br /><%= index + 1 %>. 
										  <%= c.content %>
								<% end %>

							</div><br /><hr>
							<!-- <hr> -->
						
						<!-- Comments Section Ends -->
					<% end %>	
				</div>
 			</div>
 			<!-- All Posted Listed (End) -->

 			<!-- Chat Feature (Start) -->
 			<div class="col-sm-3 sidenav">	
	    			<!-- 
 					<div class="chatheader">
 						<h2>What's On Your Mind?</h2>
 					</div>
	    			<div class="input-box">
	    				<div id="messages">
							<%=  @messages %>
						</div>
		      		    <div class="input-box">
    						<input type="text" class="input-box_text" id="message_input"/>
  						</div>
		 			</div> -->
			</div>
			
			<!-- Chat Feature (End) -->

		</div>
	</div>

		

		

	
	



		

	

app/views/blogs/landing.html.erb
<div class = 'sportheader'>
  <h2>Welcome to MadJul Sports: </h2>
</div>
  <div class="container-fluid">
    <div class="row content">
      <div class="col-md-7 col-sm-offset-2">
        <div class = "carouselcontent">
           <p>MadJul Sports where you can create new articles, chat with friends and find live sports headline feeds from around the sporting world!
            </p>
        <div class="container">
          <!-- <h1>Landing Page for MadJul Sports</h1> -->
          </div>
            <div id="myCarousel" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
              <li data-target="#myCarousel" data-slide-to="4"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">

              <div class="item active">
                <%=image_tag("Baseball/baseball1.jpg", size: "800x300", alt: "baseball")%>
              </div>

              <div class="item">
                <%=image_tag("Hockey/Hockey2.jpg", size: "800x300", alt: "hockey")%>
              </div>
            
              <div class="item">
                <%=image_tag("Golf/golf4.jpeg", size: "800x300", alt: "golf")%>
              </div>

              <div class="item">
                <%=image_tag("Football/football3.jpg", size: "800x300", alt: "football")%>
              </div>

              <div class="item">
                <%=image_tag("Basketball/basketball2.jpg", size: "800x300", alt: "basketball")%>
              </div>

            </div>


            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>








  

app/views/blogs/new.html.erb
<div class = 'sportheader'><h2>Create Sports Post:</h2></div>


<!-- Create A New Post (Start) -->

<div class="container-fluid">
	<div class="row content">
		<div class="col-md-9">
			<div class = "createcontainer">
				<%= form_for @blog do |f| %>
					<div class = "createtitle">Title: <%= f.text_field :title %></div><br />
						



					
					<div class="choosecategory">Choose Category: <%= f.collection_radio_buttons :category_id, Category.all, :id, :title %></div>
					<hr>
					<div class = "titlecontent">What's On Your Mind?:</div><br />

					<div class = "createcontent"><%= f.text_area :content, :cols => 60, :rows => 5 %>
						<div class = "contentsubmit"><%= f.submit "Create Sports Blog" %></div>
					</div>
					<br />
					<div class="imagefield">
					    <%= f.label :Upload_Images %><br>
					    <%= f.file_field :image %>
				  	</div><br>
					
					

				<% end %>
			</div>
		</div>
	</div>
</div>

<!-- Create A New Post (End) -->
 

app/views/blogs/show.html.erb
<div class = "sblogheader">
	<h2>Current Article:</h2>
</div>
<div class = "showlinks">
			<% if current_user && current_user.id === @blog.user_id %>
				<%= link_to "Create New Post" , new_blog_path %> •
				<%= link_to "Edit Post" , edit_blog_path %> •
					<%= link_to "Delete Post", blog_path, method: :delete %> 
			<% end %>
</div><br />


<div class="container-fluid">
	<div class="row content">
		<!-- Current Article Being Viewed -->
		<div class="col-md-8">
			<div class= "post-container">
				
				<img src="<%= @blog.image.url()%>">
				
				<div class = "scontent"><strong><h3>Title: <%= @blog.title %></h3></strong>

					<strong>Sport:</strong> <%= @blog.category.title %><br /><br />
					<%= @blog.content %>
				</div>

			<!-- Diplay of Current Comment Starts -->
				
				<% if current_user && current_user.id === @blog.user_id %>
					<% @blog.comments.each_with_index do |comment, index| %>
				  		<div class = "addcomments">
				  			<a href="" class="message_username"><%= current_user.email %></a><br />

				  			<%= index + 1 %>. <%= comment.content %><br /><br />
					  
						  	<%= link_to "Edit", edit_blog_comment_path(:blog_id => @blog.id, :id => comment.id) %> •

						  	<%= link_to "Delete", blog_comment_path(:blog_id => @blog.id, :id => comment.id), :method => :delete %><hr>	
						  		 	
						</div><br />
					<% end %>
				<% end %>
			<!-- Diplay of Current Comment Ends -->

			</div>
		</div>

			<!-- Created Comment Starts  -->
			<div class="col-md-3 sidenav">
				<div class= "createcomment">
					<!-- update comments -->
						<br /> <%= render 'comments/form' %><br />
				</div>	

			<!-- Created Comment Ends  -->
			</div>
	</div>
</div>

app/views/comments/_form.html.erb
				<%= form_for [@blog, @comment] do |f| %>
				  <div class = "commentheader"><%= f.label :comment %>:<br>
				  <div class = "updatecomment"><%= f.text_area :content, :cols => 50, :rows => 3 %><br><br />
				  <div class = "commentsubmit"><%= f.submit %></div>
				<% end %>
	
	

app/views/comments/edit.html.erb
<!-- Current Comment Being Edited -->
<div class = "editcommentheader"><h2> Edit Your Comments:</h2>
<div class="container-fluid">
	<div class="row content">
		<div class="col-md-9"> 
			<div class = "editcomment">
					<%= render 'comments/form' %>
			</div>
		</div>
	</div>
</div>

app/views/messages/_message.html.erb
<div class="message">
	<div><span class="message_timestamp"><br />
	    	<%= message.created_at %><br />
	  	</span>
		<strong><%= message.user.username %>: </strong><%= message.body %>
		<!-- <a href="" class="message_profile-pic"></a> -->
	</div>	
</div>
<!-- <div class="message">
  <a href="" class="message_profile-pic"></a><br />
  <a href="" class="message_username"><%= message.user.email %></a><br />
  <span class="message_timestamp">
    <%= message.created_at %><br />
  </span>
  <span class="message_star"></span>
  <span class="message_content">
    <%= message.content %>
  </span>
</div> -->

app/views/messages/create.js.erb
$("#new_message")[0].reset()