config/routes.rb
Rails.application.routes.draw do

 mount ActionCable.server => '/cable'
 
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end


  
 resources :blogs do
  resources :comments
 end

  get '/api' => "blogs#api"

  get "/profile/:id" => "profile#show", as: 'user_profile'
  get '/landing' => "blogs#landing", as: 'blogs_landing'

  patch "/users/:id", to: "user#update", as: 'edit_profile_favorites'
  
  devise_for :users
  
  root 'blogs#index'
  # resources :blogs

  resources :categories do
      member do
        put "like" => "blogs#upvote"
        put "dislike" => "blogs#downvote"
      end
  end


  resources :blogs do
      member do
        put "like" => "blogs#upvote"
        put "dislike" => "blogs#downvote"
      end
  end

  resources :users

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	acts_as_votable
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :blogs
	has_many :favorites
	has_many :users, through: :categories
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users
	has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :category

end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :chatroom
	belongs_to :user
	after_create_commit {BroadcastMessageJob.perform_later self}
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
  has_many :blogs, dependent: :destroy
  has_many :comments
  has_many :favorites
  has_many :categories, through: :favorites
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages  


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :index, :show, only:[:upvote, :downvote]
  before_action :authenticate_user!

  require 'news-api'
  
  def index
  	@blogs = Blog.all.order(:cached_votes_score => :desc)
    @messages = Message.all

  end

  def new
  	@blog = Blog.new
  end

  def create
  	
    @blog = Blog.new(blog_params)
  	@blog.user_id = current_user.id

  	if @blog.save
  		redirect_to "/"
  	else
  		render "/blogs/new"
  	end
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

    def update
      @blog = Blog.find(params[:id])
      if @blog.update(blog_params)
        redirect_to "/blogs"
      else
        render edit_blog_path
      end
    end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to "/blogs"
  end

  def upvote
    @blog.upvote_from current_user
    redirect_to blogs_path

  end

  def downvote
    @blog.downvote_from current_user
    redirect_to blogs_path
  end

  def landing
    
  end

  def api
    $newsapi = News.new("c1f1d9a225f348baab718198cab1037e")
    @top_headlines=$newsapi.get_top_headlines(sources: "espn")

    # if @top_headlines.save
    #   redirect_to "/profile/:id"
    # else
    #   render "/api"
    # end

  end

 

	private
def blog_params
	params.require(:blog).permit(:title, :content, :category_id, :user_id, :image, :remove_image)
end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  	def index
    	@comments = Comment.all
  	end
  	def new
    	@comment = Comment.new
  	end

	def create
		user = current_user
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		blog = Blog.find(params[:blog_id])
		@comment.blog_id = blog.id
		# @comment = @blog.comments.build(params[:comment])
		if @comment.save
			redirect_to "/blogs/#{params[:blog_id]}"
		else
			render "/blogs/#{params[:blog_id]}"
		end
	end


	def show
		@comment = Comment.find(params[:id])

	end

	def edit
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
	end

	
	def update
  		@blog = Blog.find(params[:blog_id])
  		@comment = @blog.comments.find(params[:id]) 
  		if @comment.update(comment_params)
    		redirect_to blog_path(@blog)
  		else
    		render :action => :edit
  		end   
	end




	def destroy
	  @blog = Blog.find(params[:blog_id])
	  @comment = @blog.comments.destroy(params[:id]) 
	redirect_to blog_path(@blog)  
 	end





	private
	
	def comment_params
		params.require(:comment).permit(:content, :user_id, :blog_id)
	end



end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@messages = Message.all
  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def update
    @user = current_user
    @user.favorites.each do |favorite|
      favorite.destroy
    end
    user_params[:category_ids].each do |id|
    	if id != ""
		    Favorite.create(user_id: @user.id, category_id: id)
    	end
    end
    redirect_to user_profile_path(@user)
  end

 


  protected

  def user_params
    params.require(:user).permit(category_ids: [])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chatroom_users_helper.rb
module ChatroomUsersHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>:
    <%= form.text_field :name %>
  </div><br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
	
<div class = "editcommentheader"><h2> Edit Chatrooms:</h2>
<div class="container-fluid">
	<div class="row content">
		<div class="col-md-9"> 
			<div class = "editcomment">

			<%= render 'form', chatroom: @chatroom %>
			<%= link_to 'Show', @chatroom %> |
			<%= link_to 'Back', chatrooms_path %>
			</div>
		</div>
	</div>
</div>

app/views/chatrooms/index.html.erb
<div class = 'sportheader'>
  <h2>Sports Chatrooms: </h2>
</div>
<p id="notice"><%= notice %></p>
<div class="fluid-container">
  <div class="row">
    <div class="col-sm-2" style="position: fixed; top 70px; left: 0;">
      <div class="chatjoin">  
        <% if user_signed_in? %>

          <h4>Chatrooms Joined:</h4>
         
            <% current_user.chatrooms.each do |chatroom| %>
             • <%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %><br />
            <% end %>
          
        <% end %>
      </div>
    </div>
    <div class="col-md-10 col-sm-offset-2" >
        <div class="newchat"><button><%= link_to 'Create New Chatroom', new_chatroom_path %></button></div>
      <!-- <div class="indexchat"><h1>Sports Chatrooms </h1> -->
        
          <div class="indexchat"><% @chatrooms.each do |chatroom| %>
              <ul>
                <strong><%= chatroom.name %>:</strong><br />
                <div class ="chatlinks">
                  <%= link_to 'Enter', chatroom %> •
                  <%= link_to 'Edit', edit_chatroom_path(chatroom) %> •
                  <%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %> •
                  <%= link_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post %> •
                  <%= link_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete %>
                </div><hr>
              </ul>
            <% end %>
             
          </div>
       
     <!--  </div> -->

    </div>
  </div>
</div>
<br>

app/views/chatrooms/new.html.erb
<div class = "editcommentheader"><h2> Create A New Chatroom:</h2>
<div class="container-fluid">
	<div class="row content">
		<div class="col-md-9"> 
			<div class = "editcomment">

			<%= render 'form', chatroom: @chatroom %>

			<%= link_to 'Back', chatrooms_path %>
			</div>
		</div>
	</div>
</div>

app/views/chatrooms/show.html.erb
<div class = 'sportheader'>
  <h2>What's On Your Mind? </h2>
</div>
<p id="notice"><%= notice %></p>
<div class="fluid-container">
  	<div class="row">
	    <div class="col-sm-2" style="position: fixed; top 70px; left: 0;">
	    	<div class="showchatjoin"> 
		    	<% if user_signed_in? %>
	        		<h4>Live Chatrooms:</h4>

			        	<% current_user.chatrooms.each do |chatroom| %>
			            	• <%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %><br />
		          	  	<% end %>
	        		
	      		<% end %>
	      	</div>
	    </div>

	    <div class="col-sm-5 col-sm-offset-3">
			<div class="chatheader">
				  <strong>Current Chatroom:</strong>
				  <%= @chatroom.name %><br />
				<%= link_to 'Edit', edit_chatroom_path(@chatroom) %> •
				<%= link_to 'Back', chatrooms_path %>
			</div>
			<div class="input-box">

	            <div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>'>
	              <div id="messages">
	                <% @messages.each do |message| %>
	                  <%= render message %>
	                <% end %> 
	              </div>
	              <div class="input-box">
	              	<%= form_for [@chatroom, Message.new], remote: true do |f| %>
	              <!-- <input type="text" class="input-box_text" id="message_input"/> -->
	             	<%= f.text_field :body, rows: 1, class: "input-box_text", autofocus: true, placeholder: 'Type a message' %> 
	              <% end %> 
	            </div>
	        </div>	
		</div>

  	</div>
</div>