config/routes.rb
Rails.application.routes.draw do

 mount ActionCable.server => '/cable'
 
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end


  
 resources :blogs do
  resources :comments
 end

  get '/api' => "blogs#api"

  get "/profile/:id" => "profile#show", as: 'user_profile'
  get '/landing' => "blogs#landing", as: 'blogs_landing'

  patch "/users/:id", to: "user#update", as: 'edit_profile_favorites'
  
  devise_for :users
  
  root 'blogs#index'
  # resources :blogs

  resources :categories do
      member do
        put "like" => "blogs#upvote"
        put "dislike" => "blogs#downvote"
      end
  end


  resources :blogs do
      member do
        put "like" => "blogs#upvote"
        put "dislike" => "blogs#downvote"
      end
  end

  resources :users

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	acts_as_votable
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :blogs
	has_many :favorites
	has_many :users, through: :categories
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users
	has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :category

end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :chatroom
	belongs_to :user
	after_create_commit {BroadcastMessageJob.perform_later self}
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
  has_many :blogs, dependent: :destroy
  has_many :comments
  has_many :favorites
  has_many :categories, through: :favorites
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages  


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :index, :show, only:[:upvote, :downvote]
  before_action :authenticate_user!

  require 'news-api'
  
  def index
  	@blogs = Blog.all.order(:cached_votes_score => :desc)
    @messages = Message.all

  end

  def new
  	@blog = Blog.new
  end

  def create
  	
    @blog = Blog.new(blog_params)
  	@blog.user_id = current_user.id

  	if @blog.save
  		redirect_to "/"
  	else
  		render "/blogs/new"
  	end
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

    def update
      @blog = Blog.find(params[:id])
      if @blog.update(blog_params)
        redirect_to "/blogs"
      else
        render edit_blog_path
      end
    end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to "/blogs"
  end

  def upvote
    @blog.upvote_from current_user
    redirect_to blogs_path

  end

  def downvote
    @blog.downvote_from current_user
    redirect_to blogs_path
  end

  def landing
    
  end

  def api
    $newsapi = News.new("c1f1d9a225f348baab718198cab1037e")
    @top_headlines=$newsapi.get_top_headlines(sources: "espn")

    # if @top_headlines.save
    #   redirect_to "/profile/:id"
    # else
    #   render "/api"
    # end

  end

 

	private
def blog_params
	params.require(:blog).permit(:title, :content, :category_id, :user_id, :image, :remove_image)
end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def update
    @user = current_user
    @user.favorites.each do |favorite|
      favorite.destroy
    end
    user_params[:category_ids].each do |id|
    	if id != ""
		    Favorite.create(user_id: @user.id, category_id: id)
    	end
    end
    redirect_to user_profile_path(@user)
  end

 


  protected

  def user_params
    params.require(:user).permit(category_ids: [])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chatroom_users_helper.rb
module ChatroomUsersHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finalindividual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://necolas.github.io/normalize.css/8.0.0/normalize.css">
    <link href="https://fonts.googleapis.com/css?family=Bitter|Lato|Roboto" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
  
  </head>

  <body>

    <header>
      <h1>MadJul Sports</h1>
    </header>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <!-- <div class="container-fluid"> -->
    <nav class= "mainnav" >
         <a class="navbar-brand" href="#">MadJul Sports</a>
        <ul class="nav navbar-nav navbar-right">
          <% if !signed_in? %>

            <li><a href='/users/sign_up'>Sign up</a></li> •
            <li><a href='/users/sign_in'>Log In</a></li>
          <% end %>
        </ul>  
        <ul class="nav navbar-nav">
          <% if signed_in? %>
            <li><%= link_to "Home", blogs_path %></li> •
            <li><%= link_to "New Post", new_blog_path %></li> •
            <li><%= link_to "Chatrooms", chatrooms_path %></li> •
            <li><%= link_to "Live Sports Feed!", api_path %></li> •
            <li><%= link_to "Edit Account",  edit_user_registration_path %></li> •
            <li><%= link_to "Sign out",destroy_user_session_path, method: :delete %></li> 
        </ul>  

        <ul class="nav navbar-nav navbar-right">
            <li><a href='/profile/<%=current_user.id %>'<%= current_user.id %>'><%= current_user.email %></a></li>
        </ul>
        <% end %>
    </nav>
      
    <nav class = "sportnav">
            <% if signed_in? %>
                      <% Category.all.each do |c|  %>
                      <%= link_to c.title, category_path(c) %> •
                      <% end %>
            <% end %>
    </nav>
  <!-- </div> -->
</nav>
  
  <hr>
    


    <div id="background"></div>
    
       <%= yield %>
 
    <div class="footer">
      <footer class="container-fluid text-center">
       <!--  <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-google"></a>
        <a href="#" class="fa fa-linkedin"></a>
        <a href="#" class="fa fa-youtube"></a>
        <a href="#" class="fa fa-instagram"></a> -->
        

      </footer>
    </div>
      
   
     

  </body>
</html>